blog/models.py
from datetime import datetime
from . import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(db.Model, UserMixin):
  __tablename__ = 'users'

  id = db.Column(db.Integer, primary_key = True)
  username = db.Column(db.String(20), unique=True, nullable=False)
  email = db.Column(db.String(100), unique=True, nullable=False)
  profile_image = db.Column(db.String(20), nullable=False, default='default.jpg')
  password = db.Column(db.String(60), nullable=False)
  posts = db.relationship('Post', backref='author', lazy=True)
  comment = db.relationship('Comments', backref='user', lazy=True)

  def __repr__(self):
    return f"User('{self.username}', '{self.email}', '{self.profile_image}' )"


class Post(db.Model):
  __tablename__ = 'posts'

  id = db.Column(db.Integer, primary_key = True)
  title = db.Column(db.String(100), nullable=False)
  date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  content = db.Column(db.Text, nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
  comment = db.relationship('Comments', backref='post', lazy=True)

  def __repr__(self):
    return f"User('{self.title}', '{self.date_posted}' )"


class Comments(db.Model):
  __tablename__ = 'comments'

  id = db.Column(db.Integer, primary_key = True)
  name = db.Column(db.String(20), unique=False, nullable=False)
  email = db.Column(db.String(100), unique=False, nullable=False)
  message = db.Column(db.Text, nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
  post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
  time_posted = db.Column(db.DateTime(), default=datetime.utcnow, index=True)

  def __repr__(self):
    return f"User('{self.message}', {self.timestamp})"

class Quotes:

  def __init__(self,author,quote):
      self.author = author
      self.quote = quote


class Email(db.Model):
  __tablename__ = 'email'

  id = db.Column(db.Integer, primary_key = True)
  email = db.Column(db.String, nullable=False, unique=True)

blog/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email, ValidationError
from blog.models import Email

class EmailSubscriptionForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()], render_kw={"placeholder": "Email..."})
    submit = SubmitField('Subscribe')

    def validate_email(self, email):
      user = Email.query.filter_by(email=email.data).first()
      if user:
        raise ValidationError('You have already subscibed!')

blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Pitch', validators=[DataRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Submit')

blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from blog.models import User


class RegistrationForm(FlaskForm):
  username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
  email = StringField('Email', validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
  submit = SubmitField('Sign Up')

  def validate_username(self, username):
      user = User.query.filter_by(username = username.data).first()
      if user:
          raise ValidationError('That username is taken. Please choose another one.')

  def validate_email(self, email):
      user = User.query.filter_by(email = email.data).first()
      if user:
          raise ValidationError('That email address already exists in the database.')

class LoginForm(FlaskForm):
  email = StringField('Email', validators=[DataRequired()])
  password = PasswordField('Password', validators=[DataRequired()])
  remember = BooleanField('Remember Me')
  submit = SubmitField('Sign In')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=5, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg','jpeg','png'])])
    submit = SubmitField('Update Account')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username = username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose another one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email = email.data).first()
            if user:
                raise ValidationError('That email address already exists in the database.')

blog/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()

def create_app(config_name):
  #initializing app
  app = Flask(__name__)

  #application configurations
  app.config.from_object(config_options[config_name])

  from .request import configure_request
  configure_request(app)

  #initializing extensions
  db.init_app(app)
  bcrypt.init_app(app)
  login_manager.init_app(app)
  mail.init_app(app)

  #registering a blueprint
  from .main import main as main_blueprint
  from .users import users as users_blueprint
  from .posts import posts as posts_blueprint

  app.register_blueprint(main_blueprint)
  app.register_blueprint(users_blueprint)
  app.register_blueprint(posts_blueprint)

  return app

blog/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

blog/main/views.py
from flask import render_template, request, redirect, flash, url_for
from . import main
from blog.models import Post
from ..request import get_quotes
from blog.main.forms import EmailSubscriptionForm
from ..models import Email
from blog import db


@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
  posts = Post.query.all()
  form = EmailSubscriptionForm()
  random_quotes = get_quotes()
  if form.validate_on_submit():
    email_subscription = Email(email=form.email.data)
    db.session.add(email_subscription)
    db.session.commit()
    flash('You have successfully subscribed to blog updates', 'success')
    return redirect(url_for('main.home'))
  else:
    flash
  return render_template('home.html', title = 'Home', posts=posts, random_quotes=random_quotes, form=form)

@main.route('/about')
def about():
  return render_template('about.html', title = 'About')

blog/posts/__init__.py
from flask import Blueprint
posts = Blueprint('posts',__name__)
from . import forms, views

blog/posts/views.py
from flask import render_template,url_for,flash, redirect, request, abort
from flask_login import current_user, login_required
from blog import db
from . import posts
from blog.models import Post, Comments, Email
from blog.posts.forms import PostForm, CommentForm
from ..email import mail_message
from blog.main.forms import EmailSubscriptionForm



@posts.route('/post/new', methods={'GET','POST'})
@login_required
def new_post():
  form = PostForm()
  if form.validate_on_submit():
    post = Post(title = form.title.data, content = form.content.data, author = current_user)
    db.session.add(post)
    db.session.commit()
    flash('Your blog-post has been created!', 'success')
    return redirect(url_for('main.home'))
  return render_template('create_post.html', title = 'Blog-Post', form = form, legend='New Blog-post')


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
  post = Post.query.get_or_404(post_id)
  form = CommentForm()
  comments = Comments.query.filter_by(post_id=post.id).order_by(Comments.time_posted.desc()).all()
  if request.method == 'POST':
    comment = Comments(name = form.name.data, email=form.email.data, message=form.message.data, post_id=post.id)
    db.session.add(comment)
    # post.comment += 1
    flash('Your comment has been submitted!', 'success')
    return redirect(url_for('posts.post', post_id=post.id))
  return render_template('post.html', title = post.title, post=post, form=form, comments=comments)


@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
  post = Post.query.get(post_id)
  if post.author != current_user:
    abort(403)
  form = PostForm()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Your blog-post has been updated!', 'success')
    return redirect(url_for('posts.post', post_id=post.id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('create_post.html', title='Update Post', form=form, legend='Update Blog Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
  post = Post.query.get(post_id)
  if post.author != current_user:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Your post has been deleted!', 'success')
  return redirect(url_for('main.home'))

@posts.route('/', methods=['GET', 'POST'])
def send_email():
  form = EmailSubscriptionForm()
  if request.method == 'POST':
    subscription_email = Email(email=form.email.data)
    db.session.add(subscription_email)
    db.session.commit()
    flash('You have succesfully subscribed to the blog post')
    return redirect(request.url)
  return render_template('home.html', form=form)

blog/users/__init__.py
from flask import Blueprint
users = Blueprint('users', __name__)
from . import forms, views

blog/users/views.py
from flask import render_template, flash, url_for, redirect, request
from blog.users.forms import LoginForm, RegistrationForm, UpdateAccountForm
from flask_login import login_required, login_user, current_user, logout_user
from . import users
from blog import db, bcrypt
from blog.models import User, Post
from .utils import save_pic


@users.route('/register', methods = ['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username = form.username.data, email = form.email.data, password = hashed_password)
    db.session.add(user)
    db.session.commit()
    flash(f'Account for was created successfully! You can now log into your account!','success') 
    return redirect(url_for('users.login'))
  return render_template('register.html', title = 'Register', form = form)


@users.route('/login', methods=['GET','POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash('Login unsuccessful. Check email or password!', 'danger')
  return render_template('login.html', title = 'Login', form = form )


@users.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateAccountForm()
  if form.validate_on_submit():
    if form.picture.data:
        picture_file = save_pic(form.picture.data)
        current_user.image_file = picture_file
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account has been updated!', 'success')
    return redirect(url_for('users.account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
  image_file = url_for('static', filename='images/' + current_user.profile_image)
  return render_template('account.html', title = 'Account', image_file=image_file, form=form)

blog/templates/about.html
{% extends 'base.html' %}
{% block content%}
<div class="about-page">
  <img src="{{ url_for('static', filename='images/image1.jpg') }}"
    style="height: 100vh; width: 100%; position: relative;" alt="">
  <div class="container about">
    <h1 class="text-center">About</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed nulla debitis suscipit, quibusdam at provident harum
      aliquid consequuntur quidem, nihil libero consectetur eos quo beatae sit odio corporis. Ab, perspiciatis?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus repellat saepe sunt atque architecto, quam,
      deserunt dolorum cum expedita fugit commodi ad eum quos praesentium asperiores. Necessitatibus repellat at quidem.
    </p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil alias laudantium eum at vel illo, accusantium
      totam
      animi molestiae deserunt cupiditate, blanditiis debitis distinctio necessitatibus quaerat architecto? Doloremque,
      nemo accusamus!</p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti a, vel consequuntur, sed consectetur id nihil
      totam illo culpa, impedit quod! Debitis necessitatibus est exercitationem eaque accusamus nemo reprehenderit quam?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero facere pariatur quas quidem rem eligendi magnam!
      Odit porro iste possimus maiores molestias. Doloribus modi laborum aut obcaecati nostrum dolores deserunt.
    </p>
  </div>
</div>
{% endblock content %}

blog/templates/account.html
{% extends 'base.html' %}
{% block content%}
<div class="container forms">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}" alt="profile picture">
    <div class="user-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p>{{ current_user.email }}</p>
    </div>
  </div>
  <div class="content">
    <form action="" enctype="multipart/form-data" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Account Info</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
          {{ form.username(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.picture.label() }} <br>
          {{ form.picture(class="form-control-field") }}
          {% if form.picture.errors %}
          {% for error in form.picture.errors %} <br>
          <span class="text-danger">{{ error }}</span><br>
          {% endfor %}
          {% endif %}
        </div>
      </fieldset>
      <div class="d-flex">
        <div class="form-group">{{ form.submit(class="btn btn-warning") }}</div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

  {% if title %}
  <title>Blog - {{ title }}</title>
  {% else %}
  <title>Blog</title>
  {% endif %}
</head>

<body>
  <div class="landing">
    <div class="navigation fixed-top">
      <div class="logo">
        <h3>Personal<span>Publisher</span>.</h3>
      </div>
      <div class="nav">
        <ul>
          <li><a href="{{ url_for('main.home') }}">Home</a></li>
          <li><a href="{{ url_for('main.about') }}">About</a></li>
        </ul>
      </div>
      <div class="sign">
        <ul>
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('posts.new_post') }}">Create Post</a></li>
          <li><a href="{{ url_for('users.account') }}">Account</a></li>
          <li><a href="{{ url_for('users.logout') }}">Sign Out</a></li>
          {% else %}
          <li><a href="{{ url_for('users.login') }}">Sign In</a></li>
          <li><a href="{{ url_for('users.register') }}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
  <main role="main">
    <div class="flash">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{category}}">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
    {% block content%}
    {% endblock content %}
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</body>

</html>

blog/templates/create_post.html
{% extends 'base.html' %}
{% block content%}
<div class="container content-section">
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
        {{ form.content(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-warning") }}
    </div>
  </form>
</div>
{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="landing-page">
  <div class="arrow">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h2 class="mt-2">Blog Posts</h2>
      {% for post in posts %}
      <div class="card mb-2">
        <div class="card-header">
          <p><a href="">{{ post.author.username }}</a></p>
        </div>
        <div class="card-body">
          <h1 class="card-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h1>
          <p>{{ post.content|truncate(200) }}</p>
        </div>
        <div class="card-footer">
          <p><small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></p>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="col-md-5">
      <h2 class="mt-2">Random Quotes</h2>
      {% for quote in random_quotes %}
      <div class="card mb-2">
        <div class="card-body">
          <p>{{ quote.author }}</p>
        </div>
        <div class="card-footer">
          <p class="text-center font-italic">Author : {{ quote.quote }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
        <h5 class="text-uppercase">Personal Publisher</h5>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum in distinctio fugiat dolorum nemo dicta,
          provident accusantium cum praesentium tempora quisquam rem at, est officiis veritatis deleniti magni
          perspiciatis asperiores.</p>
      </div>
      <div class="col-md-4">
        <h5>QUICK LINKS</h5>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="{{ url_for('users.register') }}">Create an account</a></li>
          <li><a href="{{ url_for('main.about') }}">About</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h5>SUBSCRIBE</h5>
        <div class=" text-center">
          <form action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
              {% if form.email.errors %}
              {{ form.email(class='form-control form-control-lg is-invalid') }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %}
              {{ form.email(class='form-control form-control-lg') }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.submit(class='btn btn-outline-dark') }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% block content%}
<div class="container forms">
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
      <legend>Sign In</legend>
      <div class="form-group">
        {{ form.email.label(class='form-control-label') }}
        {% if form.email.errors %}
        {{ form.email(class='form-control form-control-lg is-invalid') }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class='form-control form-control-lg') }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {% if form.password.errors %}
        {{ form.password(class='form-control form-control-lg is-invalid') }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-control form-control-lg') }}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class='form-check-input') }}
        {{ form.remember.label(class='form-control-label') }}
      </div>
      <div class="form-group">
        {{ form.submit(class='btn btn-outline-dark') }}
      </div>
      <div>
        <small class="text-muted">Don't have an account? <a href="{{ url_for('users.register') }}">Sign Up</a></small>
      </div>
    </fieldset>
  </form>
</div>
{% endblock content %}

blog/templates/post.html
{% extends 'base.html' %}
{% block content%}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="img-fluid">
        <img src="{{ url_for('static', filename='images/img3.jpg') }}" style="height:300px; width: 600px;" alt="">
      </div>
      <div>
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
      </div>
      <h5>{{ post.comments }}Comments</h5>
      {% for comment in comments %}
      <div class="comments">
        <p>{{ comment.name }} <small class="text-muted">{{ comment.time_posted }}</small></p>
        <p>{{ comment.message }}</p>
      </div>
      {% endfor %}
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-info btn-sm mt-3 mb-3" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update
          Post</a>
        <button class="btn btn-danger btn-sm m-3" data-toggle="modal" data-target="#deleteModalCenter">Delete
          Post</button>
      </div>
      {% endif %}
      <div class="col-md-8 comment">
        <h5>Leave a comment</h5>
        <form action="" method="POST">
          <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {{ form.name(class='form-control form-control-md') }}
          </div>
          <div class="form-group">
            {{ form.email.label(class='form-control-label') }}
            {{ form.email(class='form-control form-control-md') }}
          </div>
          <div class="form-group">
            {{ form.message.label(class='form-control-label') }}
            {{ form.message(class='form-control form-control-md') }}
          </div>
          <div class="form-group">
            {{ form.submit(class="btn btn-light") }}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLongTitle">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}